version: 2.0
jobs:
  build:
    docker:
      - image: membrane/bionic-membrane:latest
    environment:
      MIX_ENV: test
    working_directory: '~/app'

    steps:
      - checkout
      - run: cd basic && mix deps.get
      - run: cd basic && mix deps.compile --all
      - run: cd basic && mix format --check-formatted
      - run: cd basic && mix test
      - run: cd rtp && mix deps.get
      - run: cd rtp && mix deps.compile --all
      - run: cd rtp && mix format --check-formatted
      - run: cd rtp && mix test
      - run: cd webrtc/auth && openssl req -newkey rsa:2048 -nodes -keyout priv/certs/key.pem -x509 -days 365 -out priv/certs/certificate.pem -subj "/C=US" 
      - run: cd webrtc/auth && mix deps.get
      - run: cd webrtc/auth && mix deps.compile --all
      - run: cd webrtc/auth && mix format --check-formatted
      - run: cd webrtc/auth && mix test
      - run: cd webrtc/simple && openssl req -newkey rsa:2048 -nodes -keyout priv/certs/key.pem -x509 -days 365 -out priv/certs/certificate.pem -subj "/C=US" 
      - run: cd webrtc/simple && mix deps.get
      - run: cd webrtc/simple && mix deps.compile --all
      - run: cd webrtc/simple && mix format --check-formatted
      - run: cd webrtc/simple && mix test
