version: 2.1
orbs:
  elixir: membraneframework/elixir@1

jobs:
  lint_frontend:
    working_directory: ~/membrane_live/assets
    docker:
      - image: cimg/node:18.4.0

    steps:
      - checkout:
          path: ~/membrane_live
      - run:
          command: npm install
          name: Install front-end dependencies
      - run:
          command: npm run format:check
          name: Run prettier on front-end
      - run:
          command: npm run typing:check
          name: Run typescript typechecking on front-end
      - run:
          command: npm run lint:check
          name: Run linter on front-end

workflows:
  version: 2
  build:
    jobs:
      - elixir/build_test
      - elixir/test
      - elixir/lint:
          docs: false
          dialyzer: false
      - lint_frontend
